name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Check Code Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Code Lint `async-std`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features 'async-std-runtime' --all-targets -- -D warnings

      - name: Code Lint `tokio-runtime`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features 'tokio-runtime' --all-targets -- -D warnings

      - name: Test `http-async-std`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features 'http-async-std'

      - name: Test `http-tokio`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features 'http-tokio'

      - name: Test `ws-async-std`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features 'ws-async-std'

      - name: Test `ws-tokio`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features 'ws-tokio'
