name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Check Code Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Code Lint
        uses: actions-rs/cargo@v1
        run: cargo clippy --no-default-features --features 'async-std-runtime' --all-targets -- -D warnings
        run: cargo clippy --no-default-features --features 'tokio-runtime' --all-targets -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        #run: cargo test --no-default-features --features 'http-async-std'
        run: cargo test --no-default-features --features 'http-tokio'
        run: cargo test --no-default-features --features 'ws-async-std'
        run: cargo test --no-default-features --features 'ws-tokio'

